// File: pricelist.js
// Database ini berisi daftar harga untuk Kartini Digital.

const priceData = {
  "nama_toko": "Kartini Digital",
  "produk": [
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Art Cartoon", "harga": 7000, "keterangan": "1 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Art Cartoon", "harga": 13000, "keterangan": "2 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Art Paper", "harga": 6500, "keterangan": "1 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Art Paper", "harga": 11000, "keterangan": "2 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Concord", "harga": 9000, "keterangan": "1 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Concord", "harga": 17000, "keterangan": "2 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Cartoon Tik", "harga": 7500, "keterangan": "1 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Cartoon Tik", "harga": 13500, "keterangan": "2 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Jasmin", "harga": 11000, "keterangan": "1 Sisi" },
    { "kategori": "Cetak Kertas A3+", "nama_produk": "Jasmin", "harga": 15000, "keterangan": "2 Sisi" },
    { "kategori": "Stiker", "nama_produk": "Stiker Cromo", "harga": 10000, "keterangan": "Tanpa Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Cromo", "harga": 15000, "keterangan": "+ Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Vinyl", "harga": 12000, "keterangan": "Tanpa Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Vinyl", "harga": 17000, "keterangan": "+ Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Hologram", "harga": 25000, "keterangan": "Tanpa Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Hologram", "harga": 30000, "keterangan": "+ Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Transparan", "harga": 14000, "keterangan": "Tanpa Cutting" },
    { "kategori": "Stiker", "nama_produk": "Stiker Transparan", "harga": 19000, "keterangan": "+ Cutting" },
    { "kategori": "Cetak Kertas A3", "nama_produk": "HVS Laser A3", "harga": 6000, "keterangan": "Print Laser" },
    { "kategori": "Cetak Kertas A3", "nama_produk": "HVS Tinta Biasa A3", "harga": 3000, "keterangan": "Print Tinta Biasa" },
    { "kategori": "Print HVS", "nama_produk": "Print HVS Hitam Putih", "harga": 500, "keterangan": "Per halaman" },
    { "kategori": "Print HVS", "nama_produk": "Print HVS Warna", "harga": 1500, "keterangan": "Per halaman" },
    { "kategori": "Print HVS", "nama_produk": "Print HVS Warna Full Colour", "harga": 2000, "keterangan": "Per halaman" },
    { "kategori": "Fotocopy", "nama_produk": "Fotocopy Hitam Putih A4", "harga": 350, "keterangan": "1 sisi" },
    { "kategori": "Fotocopy", "nama_produk": "Fotocopy Hitam Putih A4", "harga": 550, "keterangan": "2 sisi" },
    { "kategori": "Fotocopy", "nama_produk": "Fotocopy Hitam Putih A3", "harga": 1500, "keterangan": "1 sisi" },
    { "kategori": "Fotocopy", "nama_produk": "Fotocopy Hitam Putih A3", "harga": 2500, "keterangan": "2 sisi" },
    { "kategori": "Stempel", "nama_produk": "Stempel", "harga": 75000, "keterangan": "1 Warna" },
    { "kategori": "Stempel", "nama_produk": "Stempel", "harga": 90000, "keterangan": "2 Warna" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Banner Flexi Cina", "harga": 30000, "keterangan": "per Meter" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Banner Flexi Korea", "harga": 60000, "keterangan": "per Meter" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Albatros", "harga": 53000, "keterangan": "Ukuran A2" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Albatros", "harga": 70000, "keterangan": "Ukuran A1" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Albatros", "harga": 90000, "keterangan": "Ukuran A0" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Glossy Paper", "harga": 68000, "keterangan": "Ukuran A2" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Glossy Paper", "harga": 85000, "keterangan": "Ukuran A1" },
    { "kategori": "Banner & Media Besar", "nama_produk": "Glossy Paper", "harga": 105000, "keterangan": "Ukuran A0" },
    { "kategori": "Cetak Massal", "nama_produk": "Brosur A4/A5", "harga": 800000, "keterangan": "1 Sisi (1 Rim)" },
    { "kategori": "Cetak Massal", "nama_produk": "Brosur A4/A5", "harga": 1200000, "keterangan": "2 Sisi (1 Rim)" },
    { "kategori": "Merchandise", "nama_produk": "Gantungan Kunci Lingkaran", "harga": 4000, "keterangan": "4.4cm" },
    { "kategori": "Merchandise", "nama_produk": "Gantungan Kunci Lingkaran", "harga": 5000, "keterangan": "5.8cm" },
    { "kategori": "Merchandise", "nama_produk": "Gantungan Kunci Akrilik", "harga": 15000, "keterangan": "Standar" },
    { "kategori": "Merchandise", "nama_produk": "Pin Peniti", "harga": 4000, "keterangan": "4.4cm" },
    { "kategori": "Merchandise", "nama_produk": "Pin Peniti", "harga": 5000, "keterangan": "5.5cm" },
    { "kategori": "Merchandise", "nama_produk": "Mug + Cetak", "harga": 25000, "keterangan": null },
    { "kategori": "Merchandise", "nama_produk": "Tumblr Termos + Cetak UV", "harga": 74000, "keterangan": null },
    { "kategori": "Merchandise", "nama_produk": "Tumblr LED + Cetak UV", "harga": 83000, "keterangan": null },
    { "kategori": "Jilid & Finishing", "nama_produk": "Hardcover", "harga": 35000, "keterangan": "Ukuran A4/B5/A5" },
    { "kategori": "Jilid & Finishing", "nama_produk": "Hardcover", "harga": 40000, "keterangan": "Ukuran F4" },
    { "kategori": "Jilid & Finishing", "nama_produk": "Hardcover", "harga": 60000, "keterangan": "Ukuran A3" },
    { "kategori": "Jilid & Finishing", "nama_produk": "Softcover", "harga": 25000, "keterangan": "Ukuran A4/B5/A5" },
    { "kategori": "Jilid & Finishing", "nama_produk": "Softcover", "harga": 35000, "keterangan": "Ukuran F4" },
    { "kategori": "Jilid & Finishing", "nama_produk": "Softcover", "harga": 50000, "keterangan": "Ukuran A3" }
  ]
};

// Baris ini membuat data di atas bisa diakses dari file lain
module.exports = priceData;